group: Pre-release checks
depends_on:
  - forge
steps:
  - label: "Check release blockers"
    key: check-release-blockers
    job_env: forge
    instance_type: small_branch
    commands:
      - bazel run //ci/ray_ci/automation:weekly_green_metric -- --check